---
title: 'Cuestionario: Encuesta Cultura Tributaria'
date: "01-12-2019"
output:
  html_document:
    includes:
      after_body: disqus.html
    number_sections: yes
    theme: flatly
  pdf_document:
    toc: true
    keep_tex: false
    template: NULL
    number_sections: true 
classoption: 
  - landscape
  - legalpaper     
geometry: "left=0.5cm,right=0.5cm,top=0.5cm,bottom=0.5cm"
editor_options: 
  chunk_output_type: console
  
header-includes:
  - \usepackage[fontsize=7pt]{scrextend}
  - \usepackage{caption}
  - \captionsetup[figure, table]{labelfont={bf},labelformat={default},labelsep=period}
  - \usepackage{graphicx}
  - \usepackage{float}
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \pagenumbering{gobble}
linestretch: '1.0'  
---

\pagebreak

# Versión 1.0: {.tabset}


<!-- [googlesheets](https://cran.r-project.org/web/packages/googlesheets/vignettes/basic-usage.html) -->

<!-- [vignette](https://cran.r-project.org/web/packages/googlesheets/vignettes/basic-usage.html#authorization-using-oauth2) -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE,warning = FALSE, include = FALSE)
options(knitr.kable.NA = '')
```


```{r }
library(googlesheets4)
library(googledrive)
library(dplyr)
library(data.table)
```


```{r eval=FALSE}
rmarkdown::render(input = "index.Rmd",output_format = "all", encoding = "UTF-8")
```


```{r eval=FALSE, warning=FALSE}
sheets_auth() # Autorizar usuario1
```


```{r, cache=TRUE, eval=FALSE}
que01<- read_sheet(ss = "https://docs.google.com/spreadsheets/d/14EBl56DcpkSe9Yk-ct8v65dfnyGTlN9cNYq0tXIg4mQ/edit#gid=661818771", sheet = 4)
save(que01,file ="data/que01.RData")
```

```{r}
load("data/que01.RData")
dat01 <- que01 %>% select(modulo,varname,pregunta,statement,values) 
fwrite(x = dat01,file = "data/quest.csv")
dat02 <- fread(file = "data/quest.csv",encoding = "UTF-8")
dat03 <- fread(file = "data/quest.csv",encoding = "UTF-8")
```

```{r include=FALSE}
# Get output document type and use as the format argument in kable function
library(knitr)
library(kableExtra)

format = if(is_html_output()) {
  "html"
} else if(is_latex_output()) {
  "latex"
}


format01 = if(is_html_output()) {
  "<br>"
} else if(is_latex_output()) {
  " \\newline "
}

format02 = if(is_html_output()) {
  "<br>"
} else if(is_latex_output()) {
  " \\\\newline "
}
```


```{r}
dat02$values<- gsub(c("="), c(") "), dat02$values)
dat02$values<- gsub(c(";"), c(format02), dat02$values)
dat02$values

dat03$values<- gsub(c("="), c(") "), dat03$values)
dat03$values<- gsub(c(";"), c("  "), dat03$values)
dat03$values
```

## Compliance {.tabset}

```{r Compliance,fig.width=6,echo=FALSE,message=FALSE,results="asis", include=FALSE}
com01<- dat03 %>% filter(modulo=="Compliance") %>% select(-"modulo")
attach(com01)
for(i in 1:dim(com01)[1]) {
  cat("  \n ",paste0("**",toupper(varname[i]),"**"))
  cat("  \n ",paste0(pregunta[i],": ",format01,ifelse(test = (statement[i]==""),yes = "",no = paste0("_**",statement[i],"**_",format01))))
  cat(paste0(values[i],format01, ifelse(test = is_latex_output(),yes = format01,no = "")))
}

com01$pregunta[duplicated(com01$pregunta)] <- NA
```


```{r Compliance2,fig.width=6,echo=FALSE,message=FALSE,results="asis", include=TRUE}
kable(com01,booktabs = T, escape=T, longtable=T,caption="Compliance", format =format) %>% 
  kable_styling(latex_options = c("repeat_header", "scale_down"),
                full_width = F,
                position = "float_left",
                font_size = 8) %>%
  column_spec(column = 1,width = "1 cm") %>%
  column_spec(column = 2,width = "14 cm") %>%
  column_spec(column = 3,width = "5 cm") %>%
  column_spec(column = 4,width = "12 cm") %>% collapse_rows(columns = c(2),valign = "middle")
```

\pagebreak
## Reform {.tabset}

```{r Reform,fig.width=6,echo=FALSE,message=FALSE,results="asis", include=FALSE}
ref01<- dat03 %>% filter(modulo=="Reform") %>% select(-"modulo")
attach(ref01)
for(i in 1:dim(ref01)[1]) {
  cat("  \n ",paste0("**",toupper(varname[i]),"**"))
  cat("  \n ",paste0(pregunta[i],": ",format01,ifelse(test = (statement[i]==""),yes = "",no = paste0("_**",statement[i],"**_",format01))))
  cat(paste0(values[i],format01, ifelse(test = is_latex_output(),yes = format01,no = "")))
}

ref01$pregunta[duplicated(ref01$pregunta)] <- NA
```


```{r Reform2,fig.width=6,echo=FALSE,message=FALSE,results="asis", include=TRUE}
kable(ref01,booktabs = T, escape=T, longtable=T,caption="Reform", format =format ) %>% 
 kable_styling(latex_options = c("repeat_header", "scale_down"),
                full_width = F,
                position = "float_left",
                font_size = 8) %>%
  column_spec(column = 1,width = "1 cm") %>%
  column_spec(column = 2,width = "14 cm") %>%
  column_spec(column = 3,width = "5 cm") %>%
  column_spec(column = 4,width = "12 cm") %>% collapse_rows(columns = c(2),valign = "middle") 
```

\pagebreak
## Social Expenditure {.tabset}

```{r Social Expenditure,fig.width=6,echo=FALSE,message=FALSE,results="asis", include=FALSE}
sec01<- dat03 %>% filter(modulo=="Social Expenditure") %>% select(-"modulo")
attach(sec01)
for(i in 1:dim(sec01)[1]) {
  cat("  \n ",paste0("**",toupper(varname[i]),"**"))
  cat("  \n ",paste0(pregunta[i],": ",format01,ifelse(test = (statement[i]==""),yes = "",no = paste0("_**",statement[i],"**_",format01))))
  cat(paste0(values[i],format01, ifelse(test = is_latex_output(),yes = format01,no = "")))
}

sec01$pregunta[duplicated(sec01$pregunta)] <- NA
```

```{r Social Expenditure2,fig.width=6,echo=FALSE,message=FALSE,results="asis", include=TRUE}
kable(sec01,booktabs = T, escape=T, longtable=T,caption="Social Expenditure", format =format ) %>% 
 kable_styling(latex_options = c("repeat_header", "scale_down"),
                full_width = F,
                position = "float_left",
                font_size = 8) %>%
  column_spec(column = 1,width = "1 cm") %>%
  column_spec(column = 2,width = "14 cm") %>%
  column_spec(column = 3,width = "5 cm") %>%
  column_spec(column = 4,width = "12 cm") %>% collapse_rows(columns = c(2),valign = "middle")
```

\pagebreak
## Knowledge consciousness {.tabset}

```{r Knowledge consciousness,fig.width=6,echo=FALSE,message=FALSE,results="asis", include=FALSE}
kno01<- dat03 %>% filter(modulo=="Knowledge consciousness") %>% select(-"modulo")
attach(kno01)
for(i in 1:dim(kno01)[1]) {
  cat("  \n ",paste0("**",toupper(varname[i]),"**"))
  cat("  \n ",paste0(pregunta[i],": ",format01,ifelse(test = (statement[i]==""),yes = "",no = paste0("_**",statement[i],"**_",format01))))
  cat(paste0(values[i],format01, ifelse(test = is_latex_output(),yes = format01,no = "")))
}
kno01$pregunta[duplicated(kno01$pregunta)] <- NA
```

```{r Knowledge consciousness2,fig.width=6,echo=FALSE,message=FALSE,results="asis", include=TRUE}
kable(kno01,booktabs = T,escape=T, longtable=T,caption="Knowledge consciousness", format =format ) %>% 
 kable_styling(latex_options = c("repeat_header", "scale_down"),
                full_width = F,
                position = "float_left",
                font_size = 8) %>%
  column_spec(column = 1,width = "1 cm") %>%
  column_spec(column = 2,width = "14 cm") %>%
  column_spec(column = 3,width = "5 cm") %>%
  column_spec(column = 4,width = "12 cm") %>% collapse_rows(columns = c(2),valign = "middle")
```

\pagebreak

## Attitudes toward Taxes {.tabset}

```{r Attitudes toward Taxes,fig.width=6,echo=FALSE,message=FALSE,results="asis", include=FALSE}
att01<- dat03 %>% filter(modulo=="Attitudes toward Taxes") %>% select(-"modulo")

attach(att01)
for(i in 1:dim(att01)[1]) {
  cat("  \n ",paste0("**",toupper(varname[i]),"**"))
  cat("  \n ",paste0(pregunta[i],": ",format01,ifelse(test = (statement[i]==""),yes = "",no = paste0("_**",statement[i],"**_",format01))))
  cat(paste0(values[i],format01, ifelse(test = is_latex_output(),yes = format01,no = "")))
}
att01$pregunta[duplicated(att01$pregunta)] <- NA
```

```{r Attitudes toward Taxes2,fig.width=6,echo=FALSE,message=FALSE,results="asis", include=TRUE}
kable(att01,booktabs = T, ,escape=T, longtable=T,caption="Attitudes toward Taxes", format =format ) %>% 
 kable_styling(latex_options = c("repeat_header", "scale_down"),
                full_width = F,
                position = "float_left",
                font_size = 8) %>%
  column_spec(column = 1,width = "1 cm") %>%
  column_spec(column = 2,width = "14 cm") %>%
  column_spec(column = 3,width = "5 cm") %>%
  column_spec(column = 4,width = "12 cm") %>% collapse_rows(columns = c(2),valign = "middle")
```

\pagebreak

## Redistribution {.tabset}

```{r Redistribution,fig.width=6,echo=FALSE,message=FALSE,results="asis", include=FALSE}
red01<- dat03 %>% filter(modulo=="Redistribution") %>% select(-"modulo")
attach(red01)
for(i in 1:dim(red01)[1]) {
  cat("  \n ",paste0("**",toupper(varname[i]),"**"))
  cat("  \n ",paste0(pregunta[i],": ",format01,ifelse(test = (statement[i]==""),yes = "",no = paste0("_**",statement[i],"**_",format01))))
  cat(paste0(values[i],format01, ifelse(test = is_latex_output(),yes = format01,no = "")))
}
red01$pregunta[duplicated(red01$pregunta)] <- NA
```

```{r Redistribution2,fig.width=6,echo=FALSE,message=FALSE,results="asis", include=TRUE}
kable(red01,booktabs = T, escape=T, longtable=T,caption="Redistribution", format =format ) %>% 
 kable_styling(latex_options = c("repeat_header", "scale_down"),
                full_width = F,
                position = "float_left",
                font_size = 8) %>%
  column_spec(column = 1,width = "1 cm") %>%
  column_spec(column = 2,width = "14 cm") %>%
  column_spec(column = 3,width = "5 cm") %>%
  column_spec(column = 4,width = "12 cm") %>% collapse_rows(columns = c(2),valign = "middle")
```


<!-- ## Social Expenditure {.tabset} -->

<!-- ```{r pressure,fig.width=6,echo=FALSE,message=FALSE,results="asis", include=TRUE} -->
<!-- attach(dat02) -->
<!-- for(i in 295:301) { -->
<!--   cat("  \n ",paste0("**",toupper(varname[i]),"**")) -->
<!--   cat("  \n ",paste0(pregunta[i],": ","<br>","_**",statement[i],"**_","<br>")) -->
<!--   cat(paste0(values[i],"<br>")) -->
<!-- } -->
<!-- ``` -->

\pagebreak
## Background vars {.tabset}

```{r}
back01 <- xlsx::read.xlsx(file = "data/background_vars.xlsx",sheetIndex = 1,encoding = "UTF-8")
```


### Sociodemográfico

```{r socdem,fig.width=6,echo=FALSE,message=FALSE,results="asis", include=TRUE}

backsocdem<- filter(back01[,c("var","values","notes")],notes=="sociodemografico")
backsocdem <- backsocdem[,c("var","values")]
kable(backsocdem, 
      linesep="",
      booktabs = T,
      escape=T, 
      longtable=T,
      caption="Background variables", 
      format =format,
      col.names = c("Pregunta","Valores")) %>%
  kable_styling(latex_options = c("repeat_header"),
                full_width = F,
                font_size = 8) %>% 
  column_spec(column = 1,width = "20 cm") %>%
  column_spec(column = 2,width = "12 cm")
```
\pagebreak
### Laboral-ocupacional

```{r laboral,fig.width=6,echo=FALSE,message=FALSE,results="asis", include=TRUE}
backlab<- filter(back01[,c("var","values","notes")],notes=="laboral-ocupacional")
backlab <- backlab[,c("var","values")]
kable(backlab, 
      linesep="",
      booktabs = T,
      escape=T, 
      longtable=T,
      caption="Background variables", 
      format =format,
      col.names = c("Pregunta","Valores")) %>%
  kable_styling(latex_options = c("repeat_header"),
                full_width = F,
                font_size = 8) %>% 
  column_spec(column = 1,width = "20 cm") %>%
  column_spec(column = 2,width = "12 cm")
```
\pagebreak
### Socioeconómico

```{r socioecon,fig.width=6,echo=FALSE,message=FALSE,results="asis", include=TRUE}
backsocecon<- filter(back01[,c("var","values","notes")],notes=="socioeconomico")
backsocecon <- backsocecon[,c("var","values")]
kable(backsocecon, 
      linesep="",
      booktabs = T,
      escape=T, 
      longtable=T,
      caption="Background variables", 
      format =format,
      col.names = c("Pregunta","Valores")) %>%
  kable_styling(latex_options = c("repeat_header"),
                full_width = F,
                font_size = 8) %>% 
  column_spec(column = 1,width = "20 cm") %>%
  column_spec(column = 2,width = "12 cm")
```





